apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: tpc-master
  name: tpc-master
  namespace: osg-services
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: tpc-master
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: tpc-master
    spec:
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/stashcache
        operator: Exists
      containers:
      - image: aaarora/tpc-master-xrootd:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        name: tpc-master
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "osg-ca-generator --host -e 365"]
        env:
        - name: TIMEFORMAT
          value: "%3R"
        - name: OSG_FQDN
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            cpu: 4
            memory: 8Gi
          requests:
            cpu: 2
            memory: 5Gi
        volumeMounts:
        - mountPath: /usr/lib/python2.7/site-packages/cagen.py
          name: cagen
          subPath: cagen.py
        - mountPath: /home/
          name: cache-vol
        - mountPath: /etc/pki/CA/private/OSG-Test-CA.key
          name: ca
          subPath: OSG-Test-CA.pem
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: stashcache.t2.ucsd.edu
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cagen
        configMap: 
          name: cagen-script-modified
      - name: ca
        secret:
          secretName: https-self-certs
          items:
          - key: OSG-Test-CA.pem
            path: OSG-Test-CA.pem
          defaultMode: 0644
      - name: cache-vol
        emptyDir: {}
