apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: tpc-chic-https
  name: tpc-chic-https
  namespace: osg-services
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: tpc-chic-https
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: tpc-chic-https
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      containers:
      - env:
        - name: XRDHTTPPORT
          value: "8443"
        - name: SITENAME
          value: EdgarSite
        image: aaarora/xrootd-tpc-https:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "dd if=/dev/zero of=/mnt/ramdisk/testSourceFile bs=1G count=10"]       
        name: tpc-chic-https
        resources:
          limits:
            cpu: 20
            memory: 50Gi
          requests:
            cpu: 10
            memory: 40Gi
        volumeMounts:
        - mountPath: /etc/grid-security/hostcert.pem
          name: certificate
          readOnly: true
          subPath: hostcert.pem
        - mountPath: /etc/grid-security/hostkey.pem
          name: hostkey
          readOnly: true
          subPath: hostkey.pem
        - mountPath: /etc/xrootd/xrootd-third-party-copy.cfg
          name: xrootd-tpc-conf-https
          subPath: xrootd-third-party-copy.cfg
        - mountPath: /mnt/ramdisk/
          name: cache-vol
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: osg.chic.nrp.internet2.edu
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certificate
        secret:
          secretName: chicago-certs
          items:
          - key: hostcert
            path: hostcert.pem
          defaultMode: 0600
      - name: hostkey
        secret:
          secretName: chicago-certs
          items:
          - key: hostkey
            path: hostkey.pem
          defaultMode: 0600
      - name: xrootd-tpc-conf-https
        configMap: 
          name: xrootd-tpc-conf-https
      - name: cache-vol
        emptyDir: {}
