resources:
  - k8s/tpc-xrootd.yaml


configMapGenerator:
  - name: cagen-script-modified
    files:
      - /home/aaarora/osg-ca-generator/lib/cagen.py
  - name: xrootd-tpc-https
    files: 
      - xrootd-third-party-copy.cfg

secretGenerator:
- name: https-self-certs
  files:
    - /home/aaarora/openssl-gencerts/OSG-Test-CA.pem

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app: xrootd-tpc
