apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: tpc-ucsd
  name: tpc-ucsd
  namespace: osg-services
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: tpc-ucsd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: tpc-ucsd
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      containers:
      - env:
        - name: XRDHTTPPORT
          value: "8080"
        - name: SITENAME
          value: EdgarSite
        image: aaarora/xrootd-tpc-http:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo Done"]       
        name: tpc-ucsd
        resources:
          limits:
            cpu: 6
            memory: 50Gi
          requests:
            cpu: 4
            memory: 40Gi
        volumeMounts:
        - mountPath: /etc/xrootd/xrootd-third-party-copy.cfg
          name: xrootd-tpc-conf
          subPath: xrootd-third-party-copy.cfg
        - mountPath: /mnt/ramdisk/
          name: cache-vol-1
        - mountPath: /mnt/ramdisk2/
          name: cache-vol-2
        - mountPath: /mnt/ramdisk3/
          name: cache-vol-3
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: stashcache.t2.ucsd.edu
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: xrootd-tpc-conf
        configMap: 
          name: xrootd-tpc-conf
      - name: cache-vol-1
        emptyDir: 
          medium: Memory
          sizeLimit: 80Gi 
      - name: cache-vol-2
        emptyDir: 
          medium: Memory
          sizeLimit: 1Gi 
      - name: cache-vol-3
        emptyDir: 
          medium: Memory
          sizeLimit: 1Gi 
