apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: tpc-ucsd
  name: tpc-ucsd
  namespace: osg-services
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: tpc-ucsd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: tpc-ucsd
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      containers:
      - env:
        - name: SITENAME
          value: TPCUCSD
        image: aaarora/xrootd-tpc-gridftp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50001
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "dd if=/dev/zero of=/mnt/ramdisk/testSourceFile bs=1G count=1"]       
        name: tpc-ucsd
        resources:
          limits:
            cpu: 5
            memory: 10Gi
          requests:
            cpu: 4
            memory: 5Gi
        volumeMounts:
        - mountPath: /etc/grid-security/clientCerts/hostcert.pem
          name: certificate
          readOnly: true
          subPath: hostcert.pem
        - mountPath: /etc/grid-security/clientCerts/hostkey.pem
          name: hostkey
          readOnly: true
          subPath: hostkey.pem
#        - mountPath: /etc/xrootd/xrootd-third-party-copy.cfg
#          name: xrootd-tpc-conf
#          subPath: xrootd-third-party-copy.cfg
        - mountPath: /mnt/ramdisk/
          name: cache-vol
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: stashcache.t2.ucsd.edu
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certificate
        secret:
          secretName: ucsd-certs
          items:
          - key: hostcert
            path: hostcert.pem
          defaultMode: 0600
      - name: hostkey
        secret:
          secretName: ucsd-certs
          items:
          - key: hostkey
            path: hostkey.pem
          defaultMode: 0600
#     - name: xrootd-tpc-conf
#        configMap: 
#          name: xrootd-tpc-conf
      - name: cache-vol
        emptyDir: {}
