apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: tpc-kans
  name: tpc-kans
  namespace: osg-services
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: tpc-kans
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: tpc-kans
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      containers:
      - env:
        - name: SITENAME
          value: TPCKANS
        image: aaarora/xrootd-tpc-gridftp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2811
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "dd if=/dev/zero of=/mnt/ramdisk/testSourceFile bs=1G count=10"]       
        name: tpc-ucsd
        resources:
          limits:
            cpu: 5
            memory: 30Gi
          requests:
            cpu: 4
            memory: 25Gi
        volumeMounts:
        - mountPath: /root/.globus/hostcert.pem
          name: certificate
          readOnly: true
          subPath: hostcert.pem
        - mountPath: /root/.globus/hostkey.pem
          name: hostkey
          readOnly: true
          subPath: hostkey.pem
        - mountPath: /mnt/ramdisk/
          name: cache-vol
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: osg.chic.nrp.internet2.edu 
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certificate
        secret:
          secretName: ucsd-certs
          items:
          - key: hostcert
            path: hostcert.pem
          defaultMode: 0600
      - name: hostkey
        secret:
          secretName: ucsd-certs
          items:
          - key: hostkey
            path: hostkey.pem
          defaultMode: 0600
      - name: cache-vol
        emptyDir: {}
