apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: tpc-master
  name: tpc-master
  namespace: osg-services
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: tpc-master
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: tpc-master
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      containers:
      - env:
        - name: SITENAME
          value: TPCUCSD
        image: aaarora/gridftp-tpc:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2811
        name: tpc-ucsd
        resources:
          limits:
            cpu: 5
            memory: 90Gi
          requests:
            cpu: 4
            memory: 80Gi
        volumeMounts:
        - mountPath: /root/.globus/hostcert.pem
          name: certificate
          readOnly: true
          subPath: hostcert.pem
        - mountPath: /root/.globus/hostkey.pem
          name: hostkey
          readOnly: true
          subPath: hostkey.pem
        - mountPath: /mnt/ramdisk/
          name: cache-vol
        - mountPath: /mnt/ramdisk2/
          name: cache-vol-2
        - mountPath: /mnt/ramdisk3/
          name: cache-vol-3
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: stashcache.t2.ucsd.edu
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certificate
        secret:
          secretName: ucsd-certs
          items:
          - key: hostcert
            path: hostcert.pem
          defaultMode: 0600
      - name: hostkey
        secret:
          secretName: ucsd-certs
          items:
          - key: hostkey
            path: hostkey.pem
          defaultMode: 0600
      - name: cache-vol
        emptyDir:
          medium: "Memory"
          sizeLimit: 25Gi
      - name: cache-vol-2
        emptyDir:
          medium: "Memory"
          sizeLimit: 25Gi
      - name: cache-vol-3
        emptyDir:
          medium: "Memory"
          sizeLimit: 25Gi
