apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tpc-gridftp
  namespace: osg-services
  labels:
    k8s-app: tpc-gridftp
spec:
  selector:
    matchLabels:
      k8s-app: tpc-gridftp
  template:
    metadata:
      labels:
        k8s-app: tpc-gridftp
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      containers:
      - env:
        - name: SITENAME
          value: TPC-GridFTP-PRPSite
        image: aaarora/gridftp-tpc:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2811
          hostPort: 2811
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "dd if=/dev/zero of=/mnt/ramdisk/testSourceFile bs=1G count=1"]       
        name: tpc-gridftp
        resources:
          limits:
            cpu: "6" 
            memory: 25Gi
#            ephemeral-storage: 40Gi
          requests:
            cpu: "4"
            memory: 20Gi
#            ephemeral-storage: 30Gi
        volumeMounts:
        - mountPath: /etc/gridftp.conf
          name: gridftp-tpc-conf
          subPath: gridftp.conf
        - mountPath: /mnt/ramdisk/
          name: cache-vol
        - mountPath: /root/.globus/hostcert.pem
          name: certificate
          readOnly: true
          subPath: hostcert.pem
        - mountPath: /root/.globus/hostkey.pem
          name: hostkey
          readOnly: true
          subPath: hostkey.pem
      dnsPolicy: ClusterFirst
      nodeSelector:
        nautilus.io/network: '100000'
#        nautilus.io/disktype: nvme
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gridftp-tpc-conf
        configMap:
          name: gridftp-tpc-conf
      - name: certificate
        secret:
          secretName: ucsd-certs
          items:
          - key: hostcert
            path: hostcert.pem
          defaultMode: 0600
      - name: hostkey
        secret:
          secretName: ucsd-certs
          items:
          - key: hostkey
            path: hostkey.pem
          defaultMode: 0600
      - name: cache-vol
        emptyDir:
          medium: Memory
          sizeLimit: 15Gi
