#!/bin/bash

## XRootD Multi Stream

/home/calcTransferRate 'HTTPS' 8
/home/sendToMaddash 'HTTPS' 8

sleep 120;

## XRootD Single Stream

/home/calcTransferRate 'HTTPS' 1
/home/sendToMaddash 'HTTPS' 1
