#!/bin/bash

## XRootD Multi Stream

/home/calcTransferRate 'XRootD' 8
/home/sendToMaddash 'XRootD' 8

sleep 120;

## XRootD Single Stream

/home/calcTransferRate 'XRootD' 1
/home/sendToMaddash 'XRootD' 1
