apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: gridftp-master
  name: gridftp-master
  namespace: osg-services
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: gridftp-master
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: gridftp-master
    spec:
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/stashcache
        operator: Exists
      containers:
      - image: aaarora/gridftp-tpc-master:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        name: gridftp-master
        resources:
          limits:
            cpu: 4
            memory: 10Gi
          requests:
            cpu: 2
            memory: 5Gi
        volumeMounts:
        - mountPath: /home/
          name: cache-vol
        - mountPath: /root/.globus/hostcert.pem
          name: certificate
          readOnly: true
          subPath: hostcert.pem
        - mountPath: /root/.globus/hostkey.pem
          name: hostkey
          readOnly: true
          subPath: hostkey.pem
        - mountPath: /home/conf.json
          name: transfer-script
          subPath: conf.json
          readOnly: false
        - mountPath: /home/calcTransferRate.py
          name: transfer-script
          subPath: calcTransferRate.py 
          readOnly: false 
        - mountPath: /home/maddash_conf.json
          name: transfer-script
          subPath: maddash_conf.json 
          readOnly: false
        - mountPath: /home/send_to_maddash.py
          name: transfer-script
          subPath: send_to_maddash.py
          readOnly: false 
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cache-vol
        emptyDir: {}
      - name: certificate
        secret:
          secretName: ucsd-certs
          items:
          - key: hostcert
            path: hostcert.pem
          defaultMode: 0600
      - name: hostkey
        secret:
          secretName: ucsd-certs
          items:
          - key: hostkey
            path: hostkey.pem
          defaultMode: 0600
      - name: transfer-script
        configMap: 
          name: gridftp-transfer-script 
          items:
          - key: conf.json
            path: conf.json
          - key: calcTransferRate.py
            path: calcTransferRate.py
          - key: maddash_conf.json
            path: maddash_conf.json
          - key: send_to_maddash.py
            path: send_to_maddash.py
          defaultMode: 0777
