apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tpc-xrootd
  namespace: osg-services
  labels:
    k8s-app: tpc-xrootd
spec:
  selector:
    matchLabels:
      k8s-app: tpc-xrootd
  template:
    metadata:
      labels:
        k8s-app: tpc-xrootd
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      containers:
      - env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: XRDHTTPPORT
          value: "8080"
        - name: SITENAME
          value: TPC-HTTP-PRPSite
        image: aaarora/xrootd-tpc-https:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          hostPort: 8080
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "dd if=/dev/zero of=/mnt/ramdisk/testSourceFile bs=1G count=1"]       
        name: tpc-xrootd
        resources:
          limits:
            cpu: "6" 
            memory: 25Gi
          requests:
            cpu: "4"
            memory: 20Gi
        volumeMounts:
        - mountPath: /etc/pki/CA/private/OSG-Test-CA.pem
          name: ca
          subPath: OSG-Test-CA.pem
        - mountPath: /usr/lib/python2.7/site-packages/cagen.py
          name: cagen
          subPath: cagen.py
        - mountPath: /etc/xrootd/xrootd-third-party-copy.cfg
          name: xrootd-tpc-https
          subPath: xrootd-third-party-copy.cfg
        - mountPath: /mnt/ramdisk/
          name: cache-vol
      dnsPolicy: ClusterFirst
      nodeSelector:
        nautilus.io/network: '100000'
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ca
        secret:
          secretName: https-self-certs
          items:
          - key: OSG-Test-CA.pem
            path: OSG-Test-CA.pem
          defaultMode: 0644
      - name: cagen
        configMap: 
          name: cagen-script-modified
      - name: xrootd-tpc-https
        configMap: 
          name: xrootd-tpc-https
      - name: cache-vol
        emptyDir:
          medium: Memory
          sizeLimit: 18Gi
