apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: tpc-kans
  name: tpc-kans
  namespace: osg-services
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: tpc-kans
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: tpc-kans
    spec:
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/stashcache
        operator: Exists
      containers:
      - env:
        - name: XRDHTTPPORT
          value: "8080"
        - name: SITENAME
          value: TPCKANS
        image: aaarora/xrootd-tpc-http:latest
        ports:
          - containerPort: 8080
            hostPort: 8080
          - containerPort: 1024
            hostPort: 1024
        lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "dd if=/dev/zero of=/mnt/ramdisk/testSourceFile bs=1G count=10"]
        imagePullPolicy: Always
        name: tpc-kans
        resources:
          limits:
            cpu: 20
            memory: 50Gi
          requests:
            cpu: 10
            memory: 40Gi
        volumeMounts:
        - mountPath: /etc/grid-security/hostcert.pem
          name: certificate
          readOnly: true
          subPath: hostcert.pem
        - mountPath: /etc/grid-security/hostkey.pem
          name: hostkey
          readOnly: true
          subPath: hostkey.pem
        - mountPath: /etc/xrootd/xrootd-third-party-copy.cfg
          name: xrootd-tpc-conf
          subPath: xrootd-third-party-copy.cfg
        - mountPath: /mnt/ramdisk/
          name: cache-vol
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: osg.kans.nrp.internet2.edu
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certificate
        secret:
          secretName: kansascity-certs
          items:
          - key: hostcert
            path: hostcert.pem
          defaultMode: 0600
      - name: hostkey
        secret:
          secretName: kansascity-certs
          items:
          - key: hostkey
            path: hostkey.pem
          defaultMode: 0600
      - name: xrootd-tpc-conf
        configMap: 
          name: xrootd-tpc-conf
      - name: cache-vol
        emptyDir: {}
